FROM continuumio/miniconda3 as build

USER root

ENV DEBIAN_FRONTEND=noninteractive 
ENV TZ=Europe/Prague

WORKDIR /tmp
COPY environment.yml .
RUN conda env create -f environment.yml 


FROM jupyterhub/k8s-singleuser-sample:1.1.3

USER root
RUN mkdir -p /home/jovyan/.kube 

COPY --from=build /opt/conda/envs /opt/conda/envs
COPY ./* /tmp

ENV PATH="/opt/conda/envs/pyenv/bin:/opt/conda/bin:$PATH"
ENV PYTHONPATH="/home/base"

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install vim -y

