FROM continuumio/miniconda3 as build

USER root

WORKDIR /tmp
COPY environment.yml .
RUN conda env create -f environment.yml
RUN /opt/conda/envs/pyenv/bin/pip install tensorflow


FROM ubuntu:20.04 

USER root

COPY --from=build /opt/conda/envs /opt/conda/envs

ENV PATH="/opt/conda/envs/pyenv/bin:/opt/conda/bin:$PATH"
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install vim -y

