#!/bin/bash

set -e

# ./monitor.sh &

pvc_path=$(df --output=target | grep home)

rsync -avz ${pvc_path}/jovyan /home

function pvc_sync_daemon {
    while inotifywait -r -e modify,create,delete,move /home/jovyan; do
        rsync -az --delete /home/jovyan $pvc_path
    done
}

pvc_sync_daemon &

exec "$@"
