#!/bin/bash

set -e

./monitor.sh &

# /usr/bin/python /usr/local/bin/jupyterhub-singleuser --ip=0.0.0.0 --port=8888 --NotebookApp.base_url=${JUPYTERHUB_SERVICE_PREFIX} --NotebookApp.token=${JPY_API_TOKEN}

exec "$@"
